version: "1"
name: example_use_case
description: "simple baseline model"
framework: random
model_type: logistic_regression
features_numeric:
  - col_num_0
  - col_num_1
  - col_num_2
  - col_num_3
  - col_num_4
  - col_num_5
  - col_num_6
  - col_num_7
  - col_num_8
features_categorical:
target: target_binary
hyper_parameters:
extra_parameters: