pipeline_name: "example_pipeline"
data_loader_cache: True
query_file_download_data: "get_data.sql"
random_state: 42
oversampling_method: smoteenn
test_size: 0.33
target_metric: f1_score
metric_lower_better: False